#!/usr/bin/env python3
"""Validate all four translations and generate the KMP catalog (no runtime dependencies)."""
import argparse
import json
import re
import runpy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'localization/strings.json'
OUTPUT = ROOT / 'android/shared/src/commonMain/kotlin/org/rhythmeta/chunithmd/shared/localization/Translations.kt'
LANGUAGES = {'zh-Hans': 'SimplifiedChinese', 'zh-Hant': 'TraditionalChinese', 'en': 'English', 'ja': 'Japanese'}

def quote(value):
    return json.dumps(value, ensure_ascii=False).replace('$', '\\$')

def generate():
    catalog = json.loads(SOURCE.read_text())
    runpy.run_path(str(ROOT / 'scripts/ios-localization.py'))['validate'](catalog)
    for key, row in catalog.items():
        assert set(row) == set(LANGUAGES), f'Missing translation: {key}'
        placeholders = sorted(re.findall(r'\{\d+\}', key))
        for tag, text in row.items():
            assert text.strip(), f'Empty {tag} translation: {key}'
            assert sorted(re.findall(r'\{\d+\}', text)) == placeholders, f'Placeholder mismatch ({tag}): {key}'
    for base in ('android/app/src/main/java', 'android/shared/src/commonMain/kotlin'):
        for path in (ROOT / base).rglob('*.kt'):
            if path == OUTPUT:
                continue
            for match in re.finditer(r'\btr\(("(?:[^"\\]|\\.)*")', path.read_text()):
                key = json.loads(match.group(1))
                assert key in catalog, f'Missing catalog key in {path}: {key}'
    lines = ['// Generated by scripts/generate-localization.py. Edit localization/strings.json instead.',
             'package org.rhythmeta.chunithmd.shared.localization', '',
             'internal val translations: Map<AppLanguage, Map<String, String>> = mapOf(']
    for tag, name in LANGUAGES.items():
        lines.append(f'    AppLanguage.{name} to {name[0].lower() + name[1:]}Strings(),')
    lines.append(')')
    for tag, name in LANGUAGES.items():
        lines.extend(['', f'private fun {name[0].lower() + name[1:]}Strings(): Map<String, String> = mapOf('])
        for key, row in sorted(catalog.items()):
            lines.append(f'    {quote(key)} to {quote(row[tag])},')
        lines.append(')')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate()
    if args.check:
        assert OUTPUT.read_text() == result, 'KMP catalog is stale; run scripts/generate-localization.py'
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(result)
    print(f'Validated {len(json.loads(SOURCE.read_text()))} strings in four languages.')
