// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/song_collection.proto
// Protobuf Java Version: 4.36.0

package org.rhythmeta.chunithmd.sharing;

/**
 * Protobuf type {@code org.rhythmeta.chunithmd.sharing.SongCollectionShare}
 */
@com.google.protobuf.Generated
public  final class SongCollectionShare extends
    com.google.protobuf.GeneratedMessageLite<
        SongCollectionShare, SongCollectionShare.Builder> implements
    // @@protoc_insertion_point(message_implements:org.rhythmeta.chunithmd.sharing.SongCollectionShare)
    SongCollectionShareOrBuilder {
  private SongCollectionShare() {
    name_ = "";
    entries_ = emptyProtobufList();
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int ENTRIES_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<org.rhythmeta.chunithmd.sharing.SongCollectionEntry> entries_;
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.rhythmeta.chunithmd.sharing.SongCollectionEntry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  public java.util.List<? extends org.rhythmeta.chunithmd.sharing.SongCollectionEntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  @java.lang.Override
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  @java.lang.Override
  public org.rhythmeta.chunithmd.sharing.SongCollectionEntry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  public org.rhythmeta.chunithmd.sharing.SongCollectionEntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }
  private void ensureEntriesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.rhythmeta.chunithmd.sharing.SongCollectionEntry> tmp = entries_;
    if (!tmp.isModifiable()) {
      entries_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  private void setEntries(
      int index, org.rhythmeta.chunithmd.sharing.SongCollectionEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureEntriesIsMutable();
    entries_.set(index, value);
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  private void addEntries(org.rhythmeta.chunithmd.sharing.SongCollectionEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureEntriesIsMutable();
    entries_.add(value);
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  private void addEntries(
      int index, org.rhythmeta.chunithmd.sharing.SongCollectionEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureEntriesIsMutable();
    entries_.add(index, value);
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  private void addAllEntries(
      java.lang.Iterable<? extends org.rhythmeta.chunithmd.sharing.SongCollectionEntry> values) {
    ensureEntriesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, entries_);
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  private void clearEntries() {
    entries_ = emptyProtobufList();
  }
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  private void removeEntries(int index) {
    ensureEntriesIsMutable();
    entries_.remove(index);
  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.rhythmeta.chunithmd.sharing.SongCollectionShare prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code org.rhythmeta.chunithmd.sharing.SongCollectionShare}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.rhythmeta.chunithmd.sharing.SongCollectionShare, Builder> implements
      // @@protoc_insertion_point(builder_implements:org.rhythmeta.chunithmd.sharing.SongCollectionShare)
      org.rhythmeta.chunithmd.sharing.SongCollectionShareOrBuilder {
    // Construct using org.rhythmeta.chunithmd.sharing.SongCollectionShare.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    @java.lang.Override
    public java.util.List<org.rhythmeta.chunithmd.sharing.SongCollectionEntry> getEntriesList() {
      return java.util.Collections.unmodifiableList(
          instance.getEntriesList());
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    @java.lang.Override
    public int getEntriesCount() {
      return instance.getEntriesCount();
    }/**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    @java.lang.Override
    public org.rhythmeta.chunithmd.sharing.SongCollectionEntry getEntries(int index) {
      return instance.getEntries(index);
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder setEntries(
        int index, org.rhythmeta.chunithmd.sharing.SongCollectionEntry value) {
      copyOnWrite();
      instance.setEntries(index, value);
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder setEntries(
        int index, org.rhythmeta.chunithmd.sharing.SongCollectionEntry.Builder builderForValue) {
      copyOnWrite();
      instance.setEntries(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder addEntries(org.rhythmeta.chunithmd.sharing.SongCollectionEntry value) {
      copyOnWrite();
      instance.addEntries(value);
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder addEntries(
        int index, org.rhythmeta.chunithmd.sharing.SongCollectionEntry value) {
      copyOnWrite();
      instance.addEntries(index, value);
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder addEntries(
        org.rhythmeta.chunithmd.sharing.SongCollectionEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addEntries(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder addEntries(
        int index, org.rhythmeta.chunithmd.sharing.SongCollectionEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addEntries(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends org.rhythmeta.chunithmd.sharing.SongCollectionEntry> values) {
      copyOnWrite();
      instance.addAllEntries(values);
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder clearEntries() {
      copyOnWrite();
      instance.clearEntries();
      return this;
    }
    /**
     * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
     */
    public Builder removeEntries(int index) {
      copyOnWrite();
      instance.removeEntries(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.rhythmeta.chunithmd.sharing.SongCollectionShare)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.rhythmeta.chunithmd.sharing.SongCollectionShare();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "entries_",
            org.rhythmeta.chunithmd.sharing.SongCollectionEntry.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.rhythmeta.chunithmd.sharing.SongCollectionShare> parser = PARSER;
        if (parser == null) {
          synchronized (org.rhythmeta.chunithmd.sharing.SongCollectionShare.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.rhythmeta.chunithmd.sharing.SongCollectionShare>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:org.rhythmeta.chunithmd.sharing.SongCollectionShare)
  private static final org.rhythmeta.chunithmd.sharing.SongCollectionShare DEFAULT_INSTANCE;
  static {
    SongCollectionShare defaultInstance = new SongCollectionShare();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SongCollectionShare.class, defaultInstance);
  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionShare getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SongCollectionShare> PARSER;

  public static com.google.protobuf.Parser<SongCollectionShare> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

