// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/song_collection.proto
// Protobuf Java Version: 4.36.0

package org.rhythmeta.chunithmd.sharing;

/**
 * Protobuf type {@code org.rhythmeta.chunithmd.sharing.SongCollectionEntry}
 */
@com.google.protobuf.Generated
public  final class SongCollectionEntry extends
    com.google.protobuf.GeneratedMessageLite<
        SongCollectionEntry, SongCollectionEntry.Builder> implements
    // @@protoc_insertion_point(message_implements:org.rhythmeta.chunithmd.sharing.SongCollectionEntry)
    SongCollectionEntryOrBuilder {
  private SongCollectionEntry() {
    songId_ = "";
    chartType_ = "";
    difficulty_ = "";
  }
  public static final int SONG_ID_FIELD_NUMBER = 1;
  private java.lang.String songId_;
  /**
   * <code>string song_id = 1;</code>
   * @return The songId.
   */
  @java.lang.Override
  public java.lang.String getSongId() {
    return songId_;
  }
  /**
   * <code>string song_id = 1;</code>
   * @return The bytes for songId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSongIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(songId_);
  }
  /**
   * <code>string song_id = 1;</code>
   * @param value The songId to set.
   */
  private void setSongId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    songId_ = value;
  }
  /**
   * <code>string song_id = 1;</code>
   */
  private void clearSongId() {

    songId_ = getDefaultInstance().getSongId();
  }
  /**
   * <code>string song_id = 1;</code>
   * @param value The bytes for songId to set.
   */
  private void setSongIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    songId_ = value.toStringUtf8();

  }

  public static final int CHART_TYPE_FIELD_NUMBER = 2;
  private java.lang.String chartType_;
  /**
   * <code>string chart_type = 2;</code>
   * @return The chartType.
   */
  @java.lang.Override
  public java.lang.String getChartType() {
    return chartType_;
  }
  /**
   * <code>string chart_type = 2;</code>
   * @return The bytes for chartType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChartTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(chartType_);
  }
  /**
   * <code>string chart_type = 2;</code>
   * @param value The chartType to set.
   */
  private void setChartType(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    chartType_ = value;
  }
  /**
   * <code>string chart_type = 2;</code>
   */
  private void clearChartType() {

    chartType_ = getDefaultInstance().getChartType();
  }
  /**
   * <code>string chart_type = 2;</code>
   * @param value The bytes for chartType to set.
   */
  private void setChartTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    chartType_ = value.toStringUtf8();

  }

  public static final int DIFFICULTY_FIELD_NUMBER = 3;
  private java.lang.String difficulty_;
  /**
   * <code>string difficulty = 3;</code>
   * @return The difficulty.
   */
  @java.lang.Override
  public java.lang.String getDifficulty() {
    return difficulty_;
  }
  /**
   * <code>string difficulty = 3;</code>
   * @return The bytes for difficulty.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDifficultyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(difficulty_);
  }
  /**
   * <code>string difficulty = 3;</code>
   * @param value The difficulty to set.
   */
  private void setDifficulty(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    difficulty_ = value;
  }
  /**
   * <code>string difficulty = 3;</code>
   */
  private void clearDifficulty() {

    difficulty_ = getDefaultInstance().getDifficulty();
  }
  /**
   * <code>string difficulty = 3;</code>
   * @param value The bytes for difficulty to set.
   */
  private void setDifficultyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    difficulty_ = value.toStringUtf8();

  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.rhythmeta.chunithmd.sharing.SongCollectionEntry prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code org.rhythmeta.chunithmd.sharing.SongCollectionEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.rhythmeta.chunithmd.sharing.SongCollectionEntry, Builder> implements
      // @@protoc_insertion_point(builder_implements:org.rhythmeta.chunithmd.sharing.SongCollectionEntry)
      org.rhythmeta.chunithmd.sharing.SongCollectionEntryOrBuilder {
    // Construct using org.rhythmeta.chunithmd.sharing.SongCollectionEntry.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string song_id = 1;</code>
     * @return The songId.
     */
    @java.lang.Override
    public java.lang.String getSongId() {
      return instance.getSongId();
    }
    /**
     * <code>string song_id = 1;</code>
     * @return The bytes for songId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSongIdBytes() {
      return instance.getSongIdBytes();
    }
    /**
     * <code>string song_id = 1;</code>
     * @param value The songId to set.
     * @return This builder for chaining.
     */
    public Builder setSongId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSongId(value);
      return this;
    }
    /**
     * <code>string song_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSongId() {
      copyOnWrite();
      instance.clearSongId();
      return this;
    }
    /**
     * <code>string song_id = 1;</code>
     * @param value The bytes for songId to set.
     * @return This builder for chaining.
     */
    public Builder setSongIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSongIdBytes(value);
      return this;
    }

    /**
     * <code>string chart_type = 2;</code>
     * @return The chartType.
     */
    @java.lang.Override
    public java.lang.String getChartType() {
      return instance.getChartType();
    }
    /**
     * <code>string chart_type = 2;</code>
     * @return The bytes for chartType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChartTypeBytes() {
      return instance.getChartTypeBytes();
    }
    /**
     * <code>string chart_type = 2;</code>
     * @param value The chartType to set.
     * @return This builder for chaining.
     */
    public Builder setChartType(
        java.lang.String value) {
      copyOnWrite();
      instance.setChartType(value);
      return this;
    }
    /**
     * <code>string chart_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChartType() {
      copyOnWrite();
      instance.clearChartType();
      return this;
    }
    /**
     * <code>string chart_type = 2;</code>
     * @param value The bytes for chartType to set.
     * @return This builder for chaining.
     */
    public Builder setChartTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChartTypeBytes(value);
      return this;
    }

    /**
     * <code>string difficulty = 3;</code>
     * @return The difficulty.
     */
    @java.lang.Override
    public java.lang.String getDifficulty() {
      return instance.getDifficulty();
    }
    /**
     * <code>string difficulty = 3;</code>
     * @return The bytes for difficulty.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDifficultyBytes() {
      return instance.getDifficultyBytes();
    }
    /**
     * <code>string difficulty = 3;</code>
     * @param value The difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficulty(
        java.lang.String value) {
      copyOnWrite();
      instance.setDifficulty(value);
      return this;
    }
    /**
     * <code>string difficulty = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDifficulty() {
      copyOnWrite();
      instance.clearDifficulty();
      return this;
    }
    /**
     * <code>string difficulty = 3;</code>
     * @param value The bytes for difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficultyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDifficultyBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.rhythmeta.chunithmd.sharing.SongCollectionEntry)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.rhythmeta.chunithmd.sharing.SongCollectionEntry();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "songId_",
            "chartType_",
            "difficulty_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.rhythmeta.chunithmd.sharing.SongCollectionEntry> parser = PARSER;
        if (parser == null) {
          synchronized (org.rhythmeta.chunithmd.sharing.SongCollectionEntry.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.rhythmeta.chunithmd.sharing.SongCollectionEntry>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:org.rhythmeta.chunithmd.sharing.SongCollectionEntry)
  private static final org.rhythmeta.chunithmd.sharing.SongCollectionEntry DEFAULT_INSTANCE;
  static {
    SongCollectionEntry defaultInstance = new SongCollectionEntry();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SongCollectionEntry.class, defaultInstance);
  }

  public static org.rhythmeta.chunithmd.sharing.SongCollectionEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SongCollectionEntry> PARSER;

  public static com.google.protobuf.Parser<SongCollectionEntry> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

