// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/song_collection.proto
// Protobuf Java Version: 4.36.0

package org.rhythmeta.chunithmd.sharing;

@com.google.protobuf.Generated
public interface SongCollectionShareOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.rhythmeta.chunithmd.sharing.SongCollectionShare)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  java.util.List<org.rhythmeta.chunithmd.sharing.SongCollectionEntry> 
      getEntriesList();
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  org.rhythmeta.chunithmd.sharing.SongCollectionEntry getEntries(int index);
  /**
   * <code>repeated .org.rhythmeta.chunithmd.sharing.SongCollectionEntry entries = 2;</code>
   */
  int getEntriesCount();
}
