// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/song_collection.proto
// Protobuf Java Version: 4.36.0

package org.rhythmeta.chunithmd.sharing;

@com.google.protobuf.Generated
public interface SongCollectionEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.rhythmeta.chunithmd.sharing.SongCollectionEntry)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string song_id = 1;</code>
   * @return The songId.
   */
  java.lang.String getSongId();
  /**
   * <code>string song_id = 1;</code>
   * @return The bytes for songId.
   */
  com.google.protobuf.ByteString
      getSongIdBytes();

  /**
   * <code>string chart_type = 2;</code>
   * @return The chartType.
   */
  java.lang.String getChartType();
  /**
   * <code>string chart_type = 2;</code>
   * @return The bytes for chartType.
   */
  com.google.protobuf.ByteString
      getChartTypeBytes();

  /**
   * <code>string difficulty = 3;</code>
   * @return The difficulty.
   */
  java.lang.String getDifficulty();
  /**
   * <code>string difficulty = 3;</code>
   * @return The bytes for difficulty.
   */
  com.google.protobuf.ByteString
      getDifficultyBytes();
}
